language: node_js
node_js:
  - v9.11.2
services:
  - postgresql
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/shoes_tests

before_script:
  - psql -c 'create database shoes_tests' -U postgres
  - psql -U postgres -d shoes_tests -a -f table.sql